<a href="https://colab.research.google.com/github/Melvinmcrn/DataScience/blob/master/PySpark/3_Pyspark_Basic_DataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!apt-get install openjdk-8-jdk-headless -qq > /dev/null
!wget -q https://downloads.apache.org/spark/spark-2.4.5/spark-2.4.5-bin-hadoop2.7.tgz
!tar xf spark-2.4.5-bin-hadoop2.7.tgz
!pip install -q findspark

In [0]:
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-2.4.5-bin-hadoop2.7"
import findspark
findspark.init()
from pyspark.sql import SparkSession
spark = SparkSession.builder.master("local[*]").getOrCreate()

# Pyspark_Basic_DataFrame

In [0]:
#1 - import module
from pyspark import SparkContext
from pyspark.sql import SparkSession
from pyspark.sql.functions import *

import numpy
import pandas

In [0]:
#2 - Create SparkContext
sc = SparkContext.getOrCreate()

sc

In [0]:
#3 - Setup SparkSession(SparkSQL)
spark = (SparkSession
         .builder
         .appName("DataFrameHandOn")
         .getOrCreate())
print(spark)

<pyspark.sql.session.SparkSession object at 0x7f07ec428350>

In [0]:
#4 - Read file to spark DataFrame
df = (spark
        .read
        .option("header","false")
        .option("inferSchema", "true")
        .csv("iris.csv"))
# If the path don't have file:/// -> it will call hdfs instead of local file system
df.cache()
print("finish caching data")

# Attribute Information:
# 1. sepal length in cm 
# 2. sepal width in cm 
# 3. petal length in cm 
# 4. petal width in cm 
# 5. class: 
# -- Iris Setosa 
# -- Iris Versicolour 
# -- Iris Virginica

finish caching data

In [0]:
#5 - Print sample 5 rows of all variables and schema
df.show(5)

print("\n")

df.printSchema()

+---+---+---+---+-----------+
|_c0|_c1|_c2|_c3|        _c4|
+---+---+---+---+-----------+
|5.1|3.5|1.4|0.2|Iris-setosa|
|4.9|3.0|1.4|0.2|Iris-setosa|
|4.7|3.2|1.3|0.2|Iris-setosa|
|4.6|3.1|1.5|0.2|Iris-setosa|
|5.0|3.6|1.4|0.2|Iris-setosa|
+---+---+---+---+-----------+
only showing top 5 rows



root
 |-- _c0: double (nullable = true)
 |-- _c1: double (nullable = true)
 |-- _c2: double (nullable = true)
 |-- _c3: double (nullable = true)
 |-- _c4: string (nullable = true)

In [0]:
df.sample(False, 0.05, 1234).toPandas()

    _c0  _c1  _c2  _c3              _c4
0   5.7  4.4  1.5  0.4      Iris-setosa
1   5.7  3.8  1.7  0.3      Iris-setosa
2   4.7  3.2  1.6  0.2      Iris-setosa
3   4.4  3.2  1.3  0.2      Iris-setosa
4   4.9  2.4  3.3  1.0  Iris-versicolor
5   5.9  3.0  4.2  1.5  Iris-versicolor
6   5.6  3.0  4.5  1.5  Iris-versicolor
7   5.8  2.7  3.9  1.2  Iris-versicolor
8   5.7  3.0  4.2  1.2  Iris-versicolor
9   6.9  3.1  5.1  2.3   Iris-virginica
10  6.8  3.2  5.9  2.3   Iris-virginica

In [0]:
df.sort('_c0').toPandas()

     _c0  _c1  _c2  _c3              _c4
0    4.3  3.0  1.1  0.1      Iris-setosa
1    4.4  2.9  1.4  0.2      Iris-setosa
2    4.4  3.0  1.3  0.2      Iris-setosa
3    4.4  3.2  1.3  0.2      Iris-setosa
4    4.5  2.3  1.3  0.3      Iris-setosa
5    4.6  3.1  1.5  0.2      Iris-setosa
6    4.6  3.4  1.4  0.3      Iris-setosa
7    4.6  3.6  1.0  0.2      Iris-setosa
8    4.6  3.2  1.4  0.2      Iris-setosa
9    4.7  3.2  1.3  0.2      Iris-setosa
10   4.7  3.2  1.6  0.2      Iris-setosa
11   4.8  3.4  1.6  0.2      Iris-setosa
12   4.8  3.0  1.4  0.1      Iris-setosa
13   4.8  3.4  1.9  0.2      Iris-setosa
14   4.8  3.1  1.6  0.2      Iris-setosa
15   4.8  3.0  1.4  0.3      Iris-setosa
16   4.9  3.0  1.4  0.2      Iris-setosa
17   4.9  3.1  1.5  0.1      Iris-setosa
18   4.9  3.1  1.5  0.1      Iris-setosa
19   4.9  3.1  1.5  0.1      Iris-setosa
20   4.9  2.4  3.3  1.0  Iris-versicolor
21   4.9  2.5  4.5  1.7   Iris-virginica
22   5.0  3.6  1.4  0.2      Iris-setosa
23   5.0  3.4  1.5  0.2      Iris-setosa
24   5.0  3.0  1.6  0.2      Iris-setosa
25   5.0  3.4  1.6  0.4      Iris-setosa
26   5.0  3.2  1.2  0.2      Iris-setosa
27   5.0  3.5  1.3  0.3      Iris-setosa
28   5.0  3.5  1.6  0.6      Iris-setosa
29   5.0  3.3  1.4  0.2      Iris-setosa
..   ...  ...  ...  ...              ...
120  6.6  2.9  4.6  1.3  Iris-versicolor
121  6.6  3.0  4.4  1.4  Iris-versicolor
122  6.7  3.1  4.4  1.4  Iris-versicolor
123  6.7  3.0  5.0  1.7  Iris-versicolor
124  6.7  3.1  4.7  1.5  Iris-versicolor
125  6.7  2.5  5.8  1.8   Iris-virginica
126  6.7  3.3  5.7  2.1   Iris-virginica
127  6.7  3.1  5.6  2.4   Iris-virginica
128  6.7  3.3  5.7  2.5   Iris-virginica
129  6.7  3.0  5.2  2.3   Iris-virginica
130  6.8  2.8  4.8  1.4  Iris-versicolor
131  6.8  3.0  5.5  2.1   Iris-virginica
132  6.8  3.2  5.9  2.3   Iris-virginica
133  6.9  3.1  4.9  1.5  Iris-versicolor
134  6.9  3.2  5.7  2.3   Iris-virginica
135  6.9  3.1  5.4  2.1   Iris-virginica
136  6.9  3.1  5.1  2.3   Iris-virginica
137  7.0  3.2  4.7  1.4  Iris-versicolor
138  7.1  3.0  5.9  2.1   Iris-virginica
139  7.2  3.6  6.1  2.5   Iris-virginica
140  7.2  3.2  6.0  1.8   Iris-virginica
141  7.2  3.0  5.8  1.6   Iris-virginica
142  7.3  2.9  6.3  1.8   Iris-virginica
143  7.4  2.8  6.1  1.9   Iris-virginica
144  7.6  3.0  6.6  2.1   Iris-virginica
145  7.7  3.8  6.7  2.2   Iris-virginica
146  7.7  2.6  6.9  2.3   Iris-virginica
147  7.7  2.8  6.7  2.0   Iris-virginica
148  7.7  3.0  6.1  2.3   Iris-virginica
149  7.9  3.8  6.4  2.0   Iris-virginica

[150 rows x 5 columns]

In [0]:
df.sort(desc('_c0')).toPandas()

     _c0  _c1  _c2  _c3              _c4
0    7.9  3.8  6.4  2.0   Iris-virginica
1    7.7  3.8  6.7  2.2   Iris-virginica
2    7.7  2.6  6.9  2.3   Iris-virginica
3    7.7  2.8  6.7  2.0   Iris-virginica
4    7.7  3.0  6.1  2.3   Iris-virginica
5    7.6  3.0  6.6  2.1   Iris-virginica
6    7.4  2.8  6.1  1.9   Iris-virginica
7    7.3  2.9  6.3  1.8   Iris-virginica
8    7.2  3.6  6.1  2.5   Iris-virginica
9    7.2  3.2  6.0  1.8   Iris-virginica
10   7.2  3.0  5.8  1.6   Iris-virginica
11   7.1  3.0  5.9  2.1   Iris-virginica
12   7.0  3.2  4.7  1.4  Iris-versicolor
13   6.9  3.1  4.9  1.5  Iris-versicolor
14   6.9  3.2  5.7  2.3   Iris-virginica
15   6.9  3.1  5.4  2.1   Iris-virginica
16   6.9  3.1  5.1  2.3   Iris-virginica
17   6.8  2.8  4.8  1.4  Iris-versicolor
18   6.8  3.0  5.5  2.1   Iris-virginica
19   6.8  3.2  5.9  2.3   Iris-virginica
20   6.7  3.1  4.4  1.4  Iris-versicolor
21   6.7  3.0  5.0  1.7  Iris-versicolor
22   6.7  3.1  4.7  1.5  Iris-versicolor
23   6.7  2.5  5.8  1.8   Iris-virginica
24   6.7  3.3  5.7  2.1   Iris-virginica
25   6.7  3.1  5.6  2.4   Iris-virginica
26   6.7  3.3  5.7  2.5   Iris-virginica
27   6.7  3.0  5.2  2.3   Iris-virginica
28   6.6  2.9  4.6  1.3  Iris-versicolor
29   6.6  3.0  4.4  1.4  Iris-versicolor
..   ...  ...  ...  ...              ...
120  5.0  3.0  1.6  0.2      Iris-setosa
121  5.0  3.4  1.6  0.4      Iris-setosa
122  5.0  3.2  1.2  0.2      Iris-setosa
123  5.0  3.5  1.3  0.3      Iris-setosa
124  5.0  3.5  1.6  0.6      Iris-setosa
125  5.0  3.3  1.4  0.2      Iris-setosa
126  5.0  2.0  3.5  1.0  Iris-versicolor
127  5.0  2.3  3.3  1.0  Iris-versicolor
128  4.9  3.0  1.4  0.2      Iris-setosa
129  4.9  3.1  1.5  0.1      Iris-setosa
130  4.9  3.1  1.5  0.1      Iris-setosa
131  4.9  3.1  1.5  0.1      Iris-setosa
132  4.9  2.4  3.3  1.0  Iris-versicolor
133  4.9  2.5  4.5  1.7   Iris-virginica
134  4.8  3.4  1.6  0.2      Iris-setosa
135  4.8  3.0  1.4  0.1      Iris-setosa
136  4.8  3.4  1.9  0.2      Iris-setosa
137  4.8  3.1  1.6  0.2      Iris-setosa
138  4.8  3.0  1.4  0.3      Iris-setosa
139  4.7  3.2  1.3  0.2      Iris-setosa
140  4.7  3.2  1.6  0.2      Iris-setosa
141  4.6  3.1  1.5  0.2      Iris-setosa
142  4.6  3.4  1.4  0.3      Iris-setosa
143  4.6  3.6  1.0  0.2      Iris-setosa
144  4.6  3.2  1.4  0.2      Iris-setosa
145  4.5  2.3  1.3  0.3      Iris-setosa
146  4.4  2.9  1.4  0.2      Iris-setosa
147  4.4  3.0  1.3  0.2      Iris-setosa
148  4.4  3.2  1.3  0.2      Iris-setosa
149  4.3  3.0  1.1  0.1      Iris-setosa

[150 rows x 5 columns]

In [0]:
#6 - change column name
renamed_df = df.selectExpr("_c0 as sepal_length", "_c1 as sepal_width", "_c2 as petal_length","_c3 as petal_width","_c4")
renamed_df = renamed_df.withColumnRenamed("_c4","label")
#6 - Print sample 5 rows of all variables
renamed_df.show(5)

print("\n")

renamed_df.printSchema()

+------------+-----------+------------+-----------+-----------+
|sepal_length|sepal_width|petal_length|petal_width|      label|
+------------+-----------+------------+-----------+-----------+
|         5.1|        3.5|         1.4|        0.2|Iris-setosa|
|         4.9|        3.0|         1.4|        0.2|Iris-setosa|
|         4.7|        3.2|         1.3|        0.2|Iris-setosa|
|         4.6|        3.1|         1.5|        0.2|Iris-setosa|
|         5.0|        3.6|         1.4|        0.2|Iris-setosa|
+------------+-----------+------------+-----------+-----------+
only showing top 5 rows



root
 |-- sepal_length: double (nullable = true)
 |-- sepal_width: double (nullable = true)
 |-- petal_length: double (nullable = true)
 |-- petal_width: double (nullable = true)
 |-- label: string (nullable = true)

In [0]:
(renamed_df
    .sample(False, 0.05, 1234)
    .toPandas())

    sepal_length  sepal_width  petal_length  petal_width            label
0            5.7          4.4           1.5          0.4      Iris-setosa
1            5.7          3.8           1.7          0.3      Iris-setosa
2            4.7          3.2           1.6          0.2      Iris-setosa
3            4.4          3.2           1.3          0.2      Iris-setosa
4            4.9          2.4           3.3          1.0  Iris-versicolor
5            5.9          3.0           4.2          1.5  Iris-versicolor
6            5.6          3.0           4.5          1.5  Iris-versicolor
7            5.8          2.7           3.9          1.2  Iris-versicolor
8            5.7          3.0           4.2          1.2  Iris-versicolor
9            6.9          3.1           5.1          2.3   Iris-virginica
10           6.8          3.2           5.9          2.3   Iris-virginica

In [0]:
#7 - create unique id
(renamed_df
    .withColumn("id",monotonically_increasing_id())
    .sample(False, 0.05, 1234) 
    .toPandas())

    sepal_length  sepal_width  petal_length  petal_width            label   id
0            5.7          4.4           1.5          0.4      Iris-setosa   15
1            5.7          3.8           1.7          0.3      Iris-setosa   18
2            4.7          3.2           1.6          0.2      Iris-setosa   29
3            4.4          3.2           1.3          0.2      Iris-setosa   42
4            4.9          2.4           3.3          1.0  Iris-versicolor   57
5            5.9          3.0           4.2          1.5  Iris-versicolor   61
6            5.6          3.0           4.5          1.5  Iris-versicolor   66
7            5.8          2.7           3.9          1.2  Iris-versicolor   82
8            5.7          3.0           4.2          1.2  Iris-versicolor   95
9            6.9          3.1           5.1          2.3   Iris-virginica  141
10           6.8          3.2           5.9          2.3   Iris-virginica  143

In [0]:
#8 - sample data
sample_df = renamed_df.sample(withReplacement=False, fraction=0.5, seed=50)
print("sample_df count : " + str(sample_df.count()))

sample_df count : 72

In [0]:
#9 - union and intersect
sample1_df = renamed_df.sample(withReplacement=False, fraction=0.5, seed=25)
sample2_df = renamed_df.sample(withReplacement=False, fraction=0.5, seed=50)
union_df = sample1_df.union(sample2_df)
intersected_df = sample1_df.intersect(sample2_df)

print("sample1_df count : " + str(sample1_df.count()))
print("sample2_df count : " + str(sample2_df.count()))
print("union_df count : " + str(union_df.count()))
print("intersected_df count : " + str(intersected_df.count()))

sample1_df count : 74
sample2_df count : 72
union_df count : 146
intersected_df count : 34

In [0]:
#10 - groupBy with count
renamed_df.groupBy("label").count().toPandas()

             label  count
0   Iris-virginica     50
1      Iris-setosa     50
2  Iris-versicolor     50

In [0]:
#11 - groupBy with average
avg_df = renamed_df.groupBy("label").avg("sepal_length")
avg_df.toPandas()

             label  avg(sepal_length)
0   Iris-virginica              6.588
1      Iris-setosa              5.006
2  Iris-versicolor              5.936

In [0]:
avg_df = renamed_df.groupBy("label").avg("sepal_length","sepal_width","petal_length","petal_width")
avg_df.toPandas()

             label  avg(sepal_length)  ...  avg(petal_length)  avg(petal_width)
0   Iris-virginica              6.588  ...              5.552             2.026
1      Iris-setosa              5.006  ...              1.464             0.244
2  Iris-versicolor              5.936  ...              4.260             1.326

[3 rows x 5 columns]

In [0]:
#12 - compute dataframe using sql command via string
renamed_df.createOrReplaceTempView("iris")
all_df = spark.sql("select * from iris")
(all_df
    .sample(False, 0.05, 1234)
    .toPandas())

    sepal_length  sepal_width  petal_length  petal_width            label
0            5.7          4.4           1.5          0.4      Iris-setosa
1            5.7          3.8           1.7          0.3      Iris-setosa
2            4.7          3.2           1.6          0.2      Iris-setosa
3            4.4          3.2           1.3          0.2      Iris-setosa
4            4.9          2.4           3.3          1.0  Iris-versicolor
5            5.9          3.0           4.2          1.5  Iris-versicolor
6            5.6          3.0           4.5          1.5  Iris-versicolor
7            5.8          2.7           3.9          1.2  Iris-versicolor
8            5.7          3.0           4.2          1.2  Iris-versicolor
9            6.9          3.1           5.1          2.3   Iris-virginica
10           6.8          3.2           5.9          2.3   Iris-virginica

In [0]:
avg_df2 = spark.sql("select label,avg(sepal_length),avg(sepal_width),avg(petal_length),avg(petal_width) from iris group by label")
avg_df2.toPandas()

             label  avg(sepal_length)  ...  avg(petal_length)  avg(petal_width)
0   Iris-virginica              6.588  ...              5.552             2.026
1      Iris-setosa              5.006  ...              1.464             0.244
2  Iris-versicolor              5.936  ...              4.260             1.326

[3 rows x 5 columns]

In [0]:
#13 - collect dataframe
avg_row_list = avg_df2.collect()
for row in avg_row_list :
    print(row)

Row(label=u'Iris-virginica', avg(sepal_length)=6.587999999999998, avg(sepal_width)=2.9739999999999998, avg(petal_length)=5.552, avg(petal_width)=2.026)
Row(label=u'Iris-setosa', avg(sepal_length)=5.005999999999999, avg(sepal_width)=3.4180000000000006, avg(petal_length)=1.464, avg(petal_width)=0.2439999999999999)
Row(label=u'Iris-versicolor', avg(sepal_length)=5.936, avg(sepal_width)=2.7700000000000005, avg(petal_length)=4.26, avg(petal_width)=1.3259999999999998)

In [0]:
#14 - row operations and properties
temp_row = avg_row_list[0]
print(row.label)
print(row["label"])
print("label" in row)
print("wrong label" in row)
print("all keys : " + str(list(row.asDict().keys())))

Iris-versicolor
Iris-versicolor
True
False
all keys : ['avg(petal_length)', 'avg(petal_width)', 'avg(sepal_width)', 'avg(sepal_length)', 'label']

In [0]:
#15 - collect dataframe as rdd
avg_row_rdd = avg_df2.rdd
for row in avg_row_rdd.collect() :
    print(row)

Row(label=u'Iris-virginica', avg(sepal_length)=6.587999999999998, avg(sepal_width)=2.9739999999999998, avg(petal_length)=5.552, avg(petal_width)=2.026)
Row(label=u'Iris-setosa', avg(sepal_length)=5.005999999999999, avg(sepal_width)=3.4180000000000006, avg(petal_length)=1.464, avg(petal_width)=0.2439999999999999)
Row(label=u'Iris-versicolor', avg(sepal_length)=5.936, avg(sepal_width)=2.7700000000000005, avg(petal_length)=4.26, avg(petal_width)=1.3259999999999998)

In [0]:
#16 - Extract row in rdd 1
avg_rdd = avg_row_rdd.map(lambda row : (row["label"],row["avg(sepal_length)"],row["avg(sepal_width)"],row["avg(petal_length)"],row["avg(petal_width)"]) )
for row in avg_rdd.collect() :
    print(row)

(u'Iris-virginica', 6.587999999999998, 2.9739999999999998, 5.552, 2.026)
(u'Iris-setosa', 5.005999999999999, 3.4180000000000006, 1.464, 0.2439999999999999)
(u'Iris-versicolor', 5.936, 2.7700000000000005, 4.26, 1.3259999999999998)

In [0]:
#17 - Extract row in rdd 2
keys = ["label","avg(sepal_length)","avg(sepal_width)","avg(petal_length)","avg(petal_width)"]
avg_rdd = avg_row_rdd.map(lambda row : [row[key] for key in keys] )
for row in avg_rdd.collect() :
    print(row)

[u'Iris-virginica', 6.587999999999998, 2.9739999999999998, 5.552, 2.026]
[u'Iris-setosa', 5.005999999999999, 3.4180000000000006, 1.464, 0.2439999999999999]
[u'Iris-versicolor', 5.936, 2.7700000000000005, 4.26, 1.3259999999999998]

In [0]:
#18 - Extract row in rdd 3
avg_rdd = avg_row_rdd.map(lambda row : [row[key] for key in row.asDict().keys()] )
for row in avg_rdd.collect() :
    print(row)

[5.552, 2.026, 2.9739999999999998, 6.587999999999998, u'Iris-virginica']
[1.464, 0.2439999999999999, 3.4180000000000006, 5.005999999999999, u'Iris-setosa']
[4.26, 1.3259999999999998, 2.7700000000000005, 5.936, u'Iris-versicolor']